### ISSUE TITLE
Max value doesn't work with color by table column

### ISSUE THREAD

**Issue by vzinche** [platybrowser/platybrowser-backend#32]
[Figure 6F](https://github.com/platybrowser/platybrowser-backend/blob/f0b39475ccf22b95e4aaabede97880f6fc509c10/data/1.0.0/misc/bookmarks.json#L340)
![Screenshot from 2020-02-18 17-14-47](https://user-images.githubusercontent.com/32451366/74754645-38bed000-5272-11ea-8d75-de5e5338f0e1.png)

**Comment by tischi** [comment]
@constantinpape 
I found an issue here.
It turns out we need **two pairs** of LUT setting values.

For example for below case:
This would be good to set decent **brightness**:

`"MinValue": 0`
`"MaxValue": 1000`

But we also need settings for how the **values in the table should be mapped onto the ColorMap**, e.g. which values should be painted red and which ones blue for a `BlueWhiteRed` colorMap.
`"ColorMapMinValue": 40`
`"ColorMapMaxValue": 0`

, where 0 and 40 relate to the value range of the `expression_sum` column.

The issue is that this only is applicable for numeric coloring models and not for categorical ones.
Thus, a bit messy.

Anyway, for now I just would add those two new values, where applicable.

So it would look like this:

```
"Figure 6F: Virtual cell assignment: gene expression level": {
    "Layers": {
      "sbem-6dpf-1-whole-raw": {},
      "sbem-6dpf-1-whole-segmented-cells": {
        "MaxValue": 500,
        "MinValue": 0,
        "Tables": [ "vc_assignments" ],
        "ColorByColumn": "expression_sum",
        "ColorMap": "Viridis"
        "ColorMapMaxValue": 40
        "ColorMapMinValue": 0
      },
      "sbem-6dpf-1-whole-segmented-outside": {}
    },
```

OK?

**Comment by tischi** [comment]
...anyway, I am implementing it already. hope this is fine 😃

**Comment by constantinpape** [comment]
> An issue is that this only is applicable for numeric coloring models and not for categorical ones.
> Thus, a bit messy. Anyway, for now I just would add those two new values, where applicable.

Ok for me.

I think we need to work a bit more on the color model at some point, but for now the solution you propose is fine.

**Comment by tischi** [comment]
> I think we need to work a bit more on the color model at some point, but for now the solution you propose is fine

Agreed.
